default: &default
  project_id: my-project-baterdene-kisi
  pubsub_topic: my-project-baterdene-topic-kisk
  pubsub_subscription: my-project-baterdene-sub-kisi

development:
  <<: *default

production:
  <<: *default
